services:
  guideon-bot:
    build: .
    container_name: guideon-v4-bot
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres:16
    container_name: guideon-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
