"""bug reports

Revision ID: 85bf297720f9
Revises: 28edcd7b37e1
Create Date: 2026-05-27 08:35:16.428495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '85bf297720f9'
down_revision: Union[str, None] = '28edcd7b37e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_tag', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_reports_guild_id'), 'bug_reports', ['guild_id'], unique=False)
    op.create_index(op.f('ix_bug_reports_user_id'), 'bug_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_reports_user_id'), table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_guild_id'), table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###