"""ticket panels + tickets

Revision ID: 2b1a5319bf4e
Revises: cbdc98acbeb3
Create Date: 2026-05-24 01:36:37.301042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2b1a5319bf4e'
down_revision: Union[str, None] = 'cbdc98acbeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('panel_message', sa.Text(), nullable=False),
    sa.Column('ticket_category_id', sa.BigInteger(), nullable=False),
    sa.Column('transcript_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('closed_category_id', sa.BigInteger(), nullable=True),
    sa.Column('ping_role_id', sa.BigInteger(), nullable=True),
    sa.Column('role_ban_ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('open_tickets_count', sa.Integer(), nullable=False),
    sa.Column('deleted_tickets_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'panel_id', name='uq_ticket_panel_guild_panel_id')
    )
    op.create_index('ix_ticket_panel_guild_message', 'ticket_panels', ['guild_id', 'message_id'], unique=False)
    op.create_index(op.f('ix_ticket_panels_guild_id'), 'ticket_panels', ['guild_id'], unique=False)
    op.create_table('ticket_panel_staff_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id_fk', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id_fk'], ['ticket_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id_fk', 'role_id', name='uq_ticket_panel_staff_role')
    )
    op.create_index(op.f('ix_ticket_panel_staff_roles_panel_id_fk'), 'ticket_panel_staff_roles', ['panel_id_fk'], unique=False)
    op.create_table('tickets',
    sa.Column('channel_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('panel_fk', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('pseudo', sa.String(length=64), nullable=True),
    sa.Column('ticket_number', sa.String(length=16), nullable=False),
    sa.Column('original_name', sa.String(length=100), nullable=False),
    sa.Column('raison', sa.Text(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.BigInteger(), nullable=False),
    sa.Column('last_rename_at', sa.BigInteger(), nullable=False),
    sa.Column('welcome_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['panel_fk'], ['ticket_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index('ix_ticket_panel_creator', 'tickets', ['panel_id', 'creator_id', 'closed'], unique=False)
    op.create_index(op.f('ix_tickets_creator_id'), 'tickets', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tickets_guild_id'), 'tickets', ['guild_id'], unique=False)
    op.create_index(op.f('ix_tickets_panel_fk'), 'tickets', ['panel_fk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_panel_fk'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_guild_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_creator_id'), table_name='tickets')
    op.drop_index('ix_ticket_panel_creator', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ticket_panel_staff_roles_panel_id_fk'), table_name='ticket_panel_staff_roles')
    op.drop_table('ticket_panel_staff_roles')
    op.drop_index(op.f('ix_ticket_panels_guild_id'), table_name='ticket_panels')
    op.drop_index('ix_ticket_panel_guild_message', table_name='ticket_panels')
    op.drop_table('ticket_panels')
    # ### end Alembic commands ###