"""système commande stat

Revision ID: 2a41b131200f
Revises: f46b8680d144
Create Date: 2026-06-20 00:05:31.372872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2a41b131200f'
down_revision: Union[str, None] = 'f46b8680d144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_stats_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('command_name', sa.String(length=64), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_name', 'stat_date', name='uq_command_stats_daily_cmd_date')
    )
    op.create_index('ix_command_stats_daily_command', 'command_stats_daily', ['command_name'], unique=False)
    op.create_index('ix_command_stats_daily_date', 'command_stats_daily', ['stat_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_command_stats_daily_date', table_name='command_stats_daily')
    op.drop_index('ix_command_stats_daily_command', table_name='command_stats_daily')
    op.drop_table('command_stats_daily')
    # ### end Alembic commands ###