"""alpha_journaliste_rank_emoji

Revision ID: ae31b997ab20
Revises: 2e28ee77bb7c
Create Date: 2026-06-09 11:33:34.524786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ae31b997ab20'
down_revision: Union[str, None] = '2e28ee77bb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alpha_rank_configs', sa.Column('rank_emoji', sa.String(length=100), nullable=True))
    op.add_column('alpha_staff', sa.Column('is_journaliste', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alpha_staff', 'is_journaliste')
    op.drop_column('alpha_rank_configs', 'rank_emoji')
    # ### end Alembic commands ###