"""alpha_content_config

Revision ID: 1d83aa159cd7
Revises: 8cd35551df76
Create Date: 2026-06-03 09:00:01.150892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1d83aa159cd7'
down_revision: Union[str, None] = '8cd35551df76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alpha_rank_configs', sa.Column('content_nous_rejoindre_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_nous_rejoindre_ping_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_nous_rejoindre_emoji_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_index_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_index_emoji_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_regle_interne_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_regle_interne_emoji_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alpha_rank_configs', 'content_regle_interne_emoji_id')
    op.drop_column('alpha_rank_configs', 'content_regle_interne_channel_id')
    op.drop_column('alpha_rank_configs', 'content_index_emoji_id')
    op.drop_column('alpha_rank_configs', 'content_index_channel_id')
    op.drop_column('alpha_rank_configs', 'content_nous_rejoindre_emoji_id')
    op.drop_column('alpha_rank_configs', 'content_nous_rejoindre_ping_id')
    op.drop_column('alpha_rank_configs', 'content_nous_rejoindre_channel_id')
    # ### end Alembic commands ###