"""shop_entries + bienvenue_configs + command_controls

Revision ID: c9ee5c84df96
Revises: 
Create Date: 2026-05-20 22:09:33.357160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'c9ee5c84df96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bienvenue_configs',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('system_active', sa.Boolean(), nullable=False),
    sa.Column('arrive_active', sa.Boolean(), nullable=False),
    sa.Column('depart_active', sa.Boolean(), nullable=False),
    sa.Column('arrive_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('depart_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('arrive_message', sa.Text(), nullable=False),
    sa.Column('depart_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('command_controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_name')
    )
    op.create_table('shop_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('VIP', 'GOLD_PLUS', name='shop_role', native_enum=False, length=16), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'discord_id', name='uq_shop_role_discord_id')
    )
    op.create_index(op.f('ix_shop_entries_role'), 'shop_entries', ['role'], unique=False)
    op.create_index('ix_shop_role_discord', 'shop_entries', ['role', 'discord_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shop_role_discord', table_name='shop_entries')
    op.drop_index(op.f('ix_shop_entries_role'), table_name='shop_entries')
    op.drop_table('shop_entries')
    op.drop_table('command_controls')
    op.drop_table('bienvenue_configs')
    # ### end Alembic commands ###