"""alpha_rank_config

Revision ID: 8cd35551df76
Revises: da72d680f34d
Create Date: 2026-06-02 20:19:31.365799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8cd35551df76'
down_revision: Union[str, None] = 'da72d680f34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha_rank_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('journaliste_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('dev_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('journaliste_ping_id', sa.BigInteger(), nullable=True),
    sa.Column('dev_ping_id', sa.BigInteger(), nullable=True),
    sa.Column('role_journaliste_id', sa.BigInteger(), nullable=True),
    sa.Column('role_guide_id', sa.BigInteger(), nullable=True),
    sa.Column('role_moderateur_test_id', sa.BigInteger(), nullable=True),
    sa.Column('role_moderateur_confirme_id', sa.BigInteger(), nullable=True),
    sa.Column('role_moderateur_plus_id', sa.BigInteger(), nullable=True),
    sa.Column('role_super_moderateur_id', sa.BigInteger(), nullable=True),
    sa.Column('role_administrateur_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('alpha_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('pseudo_jeu', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('skin_head_emoji', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index('ix_alpha_staff_grade', 'alpha_staff', ['grade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alpha_staff_grade', table_name='alpha_staff')
    op.drop_table('alpha_staff')
    op.drop_table('alpha_rank_configs')
    # ### end Alembic commands ###