"""autorole config

Revision ID: ad0a5f5610c9
Revises: 2b1a5319bf4e
Create Date: 2026-05-25 18:35:33.552927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ad0a5f5610c9'
down_revision: Union[str, None] = '2b1a5319bf4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autorole_configs',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role_id_1', sa.BigInteger(), nullable=True),
    sa.Column('role_id_2', sa.BigInteger(), nullable=True),
    sa.Column('role_id_3', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autorole_configs')
    # ### end Alembic commands ###