"""autorole + reaction_role

Revision ID: 28edcd7b37e1
Revises: ad0a5f5610c9
Create Date: 2026-05-26 08:10:10.389854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '28edcd7b37e1'
down_revision: Union[str, None] = 'ad0a5f5610c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_role_messages',
    sa.Column('message_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_reaction_role_messages_guild_id'), 'reaction_role_messages', ['guild_id'], unique=False)
    op.create_table('reaction_role_couples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_fk', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['message_fk'], ['reaction_role_messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_fk', 'emoji', name='uq_reaction_role_couple_emoji')
    )
    op.create_index('ix_reaction_role_couple_lookup', 'reaction_role_couples', ['message_fk', 'emoji'], unique=False)
    op.create_index(op.f('ix_reaction_role_couples_message_fk'), 'reaction_role_couples', ['message_fk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaction_role_couples_message_fk'), table_name='reaction_role_couples')
    op.drop_index('ix_reaction_role_couple_lookup', table_name='reaction_role_couples')
    op.drop_table('reaction_role_couples')
    op.drop_index(op.f('ix_reaction_role_messages_guild_id'), table_name='reaction_role_messages')
    op.drop_table('reaction_role_messages')
    # ### end Alembic commands ###