"""shop_entries + bienvenue_configs + command_controls

Revision ID: 0d5468552ea9
Revises: c9ee5c84df96
Create Date: 2026-05-20 22:12:27.586991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '0d5468552ea9'
down_revision: Union[str, None] = 'c9ee5c84df96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###