"""maj Alpha

Revision ID: bd745c3296a3
Revises: 387a73ab5655
Create Date: 2026-06-19 20:21:24.055411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'bd745c3296a3'
down_revision: Union[str, None] = '387a73ab5655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###