"""invite +birthday

Revision ID: 00ac91faadec
Revises: 85bf297720f9
Create Date: 2026-05-31 14:40:34.337404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '00ac91faadec'
down_revision: Union[str, None] = '85bf297720f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday_configs',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('birthday_users',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_index('ix_birthday_users_guild_month_day', 'birthday_users', ['guild_id', 'month', 'day'], unique=False)
    op.create_table('invite_configs',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reward_role_id', sa.BigInteger(), nullable=True),
    sa.Column('reward_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('invite_links',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('inviter_id', sa.BigInteger(), nullable=True),
    sa.Column('invite_code', sa.String(length=50), nullable=True),
    sa.Column('is_fake', sa.Boolean(), nullable=False),
    sa.Column('counted_left', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'member_id')
    )
    op.create_index('ix_invite_links_inviter', 'invite_links', ['guild_id', 'inviter_id'], unique=False)
    op.create_table('invite_stats',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('regular', sa.Integer(), nullable=False),
    sa.Column('fake', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('left', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_index('ix_invite_stats_guild', 'invite_stats', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invite_stats_guild', table_name='invite_stats')
    op.drop_table('invite_stats')
    op.drop_index('ix_invite_links_inviter', table_name='invite_links')
    op.drop_table('invite_links')
    op.drop_table('invite_configs')
    op.drop_index('ix_birthday_users_guild_month_day', table_name='birthday_users')
    op.drop_table('birthday_users')
    op.drop_table('birthday_configs')
    # ### end Alembic commands ###