"""check

Revision ID: 483bbb22c16a
Revises: 49515e366312
Create Date: 2026-07-03 22:12:41.134280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '483bbb22c16a'
down_revision: Union[str, None] = '49515e366312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alpha_staff', sa.Column('blames', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alpha_staff', 'blames')
    # ### end Alembic commands ###