"""bienvenue format et image personnalisee

Revision ID: bf2fb26d2c20
Revises: 483bbb22c16a
Create Date: 2026-07-10 23:27:39.563813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'bf2fb26d2c20'
down_revision: Union[str, None] = '483bbb22c16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bienvenue_configs', sa.Column('arrive_format', sa.Text(), server_default='embed', nullable=False))
    op.add_column('bienvenue_configs', sa.Column('depart_format', sa.Text(), server_default='embed', nullable=False))
    op.add_column('bienvenue_configs', sa.Column('arrive_image_url', sa.Text(), nullable=True))
    op.add_column('bienvenue_configs', sa.Column('depart_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bienvenue_configs', 'depart_image_url')
    op.drop_column('bienvenue_configs', 'arrive_image_url')
    op.drop_column('bienvenue_configs', 'depart_format')
    op.drop_column('bienvenue_configs', 'arrive_format')
    # ### end Alembic commands ###