"""permission_entries

Revision ID: cbdc98acbeb3
Revises: 0d5468552ea9
Create Date: 2026-05-21 19:34:39.312805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'cbdc98acbeb3'
down_revision: Union[str, None] = '0d5468552ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('DEV', 'STAFF_GUIDEON', 'OP_ALPHA', name='permission_role', native_enum=False, length=32), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'discord_id', name='uq_permission_role_discord_id')
    )
    op.create_index(op.f('ix_permission_entries_role'), 'permission_entries', ['role'], unique=False)
    op.create_index('ix_permission_role_discord', 'permission_entries', ['role', 'discord_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_permission_role_discord', table_name='permission_entries')
    op.drop_index(op.f('ix_permission_entries_role'), table_name='permission_entries')
    op.drop_table('permission_entries')
    # ### end Alembic commands ###