"""maj Alpha

Revision ID: 387a73ab5655
Revises: ff04ee04161a
Create Date: 2026-06-19 18:19:02.484728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '387a73ab5655'
down_revision: Union[str, None] = 'ff04ee04161a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alpha_rank_configs', sa.Column('role_affilie_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('role_builder_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('role_equipe_id', sa.BigInteger(), nullable=True))
    op.add_column('alpha_staff', sa.Column('is_affilie', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('alpha_staff', sa.Column('is_builder', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('alpha_staff', sa.Column('pseudo_jeu_builder', sa.String(length=64), nullable=True))
    op.alter_column('alpha_staff', 'grade',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alpha_staff', 'grade',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('alpha_staff', 'pseudo_jeu_builder')
    op.drop_column('alpha_staff', 'is_builder')
    op.drop_column('alpha_staff', 'is_affilie')
    op.drop_column('alpha_rank_configs', 'role_equipe_id')
    op.drop_column('alpha_rank_configs', 'role_builder_id')
    op.drop_column('alpha_rank_configs', 'role_affilie_id')
    # ### end Alembic commands ###