"""ngstaff: ping optionnel dans l'annonce publique de rank/derank

Revision ID: e50aea6b444b
Revises: 9bf24b7cf7d4
Create Date: 2026-10-10

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e50aea6b444b'
down_revision: Union[str, None] = '9bf24b7cf7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ng_rank_configs',
        sa.Column('rank_ping_id', sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ng_rank_configs', 'rank_ping_id')
    # ### end Alembic commands ###
