"""onu alpha

Revision ID: 341b2bf6608e
Revises: ae31b997ab20
Create Date: 2026-06-09 12:10:46.087004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '341b2bf6608e'
down_revision: Union[str, None] = 'ae31b997ab20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha_onu_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('jour_onu', sa.Integer(), nullable=True),
    sa.Column('pre_heure', sa.Integer(), nullable=True),
    sa.Column('pre_minute', sa.Integer(), nullable=True),
    sa.Column('ann_heure', sa.Integer(), nullable=True),
    sa.Column('ann_minute', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Europe/Paris', nullable=False),
    sa.Column('ping_mp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('image_name', sa.String(length=100), nullable=True),
    sa.Column('join_url', sa.String(length=300), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('alpha_onu_ping_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'discord_id', name='uq_onu_ping_member')
    )
    op.create_index('ix_onu_ping_guild', 'alpha_onu_ping_members', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_onu_ping_guild', table_name='alpha_onu_ping_members')
    op.drop_table('alpha_onu_ping_members')
    op.drop_table('alpha_onu_configs')
    # ### end Alembic commands ###