"""giveaway

Revision ID: 084793c9ed56
Revises: 00ac91faadec
Create Date: 2026-06-01 08:37:02.672471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '084793c9ed56'
down_revision: Union[str, None] = '00ac91faadec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaway_blacklist',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_index('ix_giveaway_blacklist_guild', 'giveaway_blacklist', ['guild_id'], unique=False)
    op.create_table('giveaway_participants',
    sa.Column('giveaway_id', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('giveaway_id', 'user_id')
    )
    op.create_index('ix_giveaway_participants_giveaway', 'giveaway_participants', ['giveaway_id'], unique=False)
    op.create_table('giveaways',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('prize', sa.String(length=500), nullable=False),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('winners', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_giveaways_guild', 'giveaways', ['guild_id'], unique=False)
    op.create_index('ix_giveaways_guild_ended', 'giveaways', ['guild_id', 'ended'], unique=False)
    op.create_index('ix_giveaways_guild_msg', 'giveaways', ['guild_id', 'message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_giveaways_guild_msg', table_name='giveaways')
    op.drop_index('ix_giveaways_guild_ended', table_name='giveaways')
    op.drop_index('ix_giveaways_guild', table_name='giveaways')
    op.drop_table('giveaways')
    op.drop_index('ix_giveaway_participants_giveaway', table_name='giveaway_participants')
    op.drop_table('giveaway_participants')
    op.drop_index('ix_giveaway_blacklist_guild', table_name='giveaway_blacklist')
    op.drop_table('giveaway_blacklist')
    # ### end Alembic commands ###