"""alpha_content_config

Revision ID: 2e28ee77bb7c
Revises: 1d83aa159cd7
Create Date: 2026-06-03 09:17:54.118825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2e28ee77bb7c'
down_revision: Union[str, None] = '1d83aa159cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alpha_rank_configs', sa.Column('content_nous_rejoindre_emoji', sa.String(length=100), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_index_emoji', sa.String(length=100), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_regle_interne_emoji', sa.String(length=100), nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_stafflist_channel_id', sa.BigInteger(), nullable=True))
    op.drop_column('alpha_rank_configs', 'content_nous_rejoindre_emoji_id')
    op.drop_column('alpha_rank_configs', 'content_regle_interne_emoji_id')
    op.drop_column('alpha_rank_configs', 'content_index_emoji_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alpha_rank_configs', sa.Column('content_index_emoji_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_regle_interne_emoji_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('alpha_rank_configs', sa.Column('content_nous_rejoindre_emoji_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('alpha_rank_configs', 'content_stafflist_channel_id')
    op.drop_column('alpha_rank_configs', 'content_regle_interne_emoji')
    op.drop_column('alpha_rank_configs', 'content_index_emoji')
    op.drop_column('alpha_rank_configs', 'content_nous_rejoindre_emoji')
    # ### end Alembic commands ###