"""invite +announce config (qui a invité qui)

Revision ID: f4bd94e3609d
Revises: e3b7f1a9d5c2
Create Date: 2026-09-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f4bd94e3609d'
down_revision: Union[str, None] = 'e3b7f1a9d5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_DEFAULT_ANNOUNCE_MESSAGE = (
    "{mention} a été invité par {inviter} sur le serveur, "
    "nous sommes maintenant **{member_count}**."
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'invite_configs',
        sa.Column('announce_active', sa.Boolean(), server_default='false', nullable=False),
    )
    op.add_column(
        'invite_configs',
        sa.Column('announce_channel_id', sa.BigInteger(), nullable=True),
    )
    op.add_column(
        'invite_configs',
        sa.Column('announce_message', sa.Text(), server_default=_DEFAULT_ANNOUNCE_MESSAGE, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_configs', 'announce_message')
    op.drop_column('invite_configs', 'announce_channel_id')
    op.drop_column('invite_configs', 'announce_active')
    # ### end Alembic commands ###