"""alpha_role_react

Revision ID: f7e3f444cd77
Revises: 9194c5a46fa7
Create Date: 2026-06-12 15:54:39.954438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f7e3f444cd77'
down_revision: Union[str, None] = '9194c5a46fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha_role_react_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('alpha_role_react_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'position', name='uq_role_react_pos'),
    sa.UniqueConstraint('guild_id', 'role_id', name='uq_role_react_role')
    )
    op.create_index('ix_role_react_guild', 'alpha_role_react_entries', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_react_guild', table_name='alpha_role_react_entries')
    op.drop_table('alpha_role_react_entries')
    op.drop_table('alpha_role_react_configs')
    # ### end Alembic commands ###