"""notations

Revision ID: 9194c5a46fa7
Revises: 341b2bf6608e
Create Date: 2026-06-09 16:52:41.522481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9194c5a46fa7'
down_revision: Union[str, None] = '341b2bf6608e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha_nota_availabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'discord_id', name='uq_nota_availability')
    )
    op.create_index('ix_nota_avail_guild', 'alpha_nota_availabilities', ['guild_id'], unique=False)
    op.create_table('alpha_nota_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_public_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_logs_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('countries_count', sa.Integer(), server_default='238', nullable=False),
    sa.Column('send_presence_weekday', sa.Integer(), nullable=True),
    sa.Column('send_presence_hour', sa.Integer(), nullable=True),
    sa.Column('send_presence_minute', sa.Integer(), nullable=True),
    sa.Column('deadline_weekday', sa.Integer(), nullable=True),
    sa.Column('deadline_hour', sa.Integer(), nullable=True),
    sa.Column('deadline_minute', sa.Integer(), nullable=True),
    sa.Column('send_public_weekday', sa.Integer(), nullable=True),
    sa.Column('send_public_hour', sa.Integer(), nullable=True),
    sa.Column('send_public_minute', sa.Integer(), nullable=True),
    sa.Column('url_country_lookup', sa.String(length=300), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('alpha_nota_history',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('last_range_start', sa.Integer(), nullable=True),
    sa.Column('last_range_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'discord_id')
    )
    op.create_table('alpha_nota_week_states',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('availability_message_id', sa.BigInteger(), nullable=True),
    sa.Column('public_message_id', sa.BigInteger(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assigned_ranges', sa.Text(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alpha_nota_week_states')
    op.drop_table('alpha_nota_history')
    op.drop_table('alpha_nota_configs')
    op.drop_index('ix_nota_avail_guild', table_name='alpha_nota_availabilities')
    op.drop_table('alpha_nota_availabilities')
    # ### end Alembic commands ###