import asyncio
from utils.db.engine import get_session
from utils.db.models.control_admin import CommandControl

COMMANDS = {
    "ng_autel": True,
    "ng_convert": True,
    "ng_rd": True,
    "ng_serveur_stat": True,
    "ng_skin": True,
    "ng_info": True,
    "ng_claim": False,
    "ng_classement": False,
    "ng_sanction": True,
    "ng_note_archi": True,
    "ng_country": True,
    "ng_mmr": True,
    "ng_profil": True,
    "ng_lvl": True,
    "ng_pillage": True,
    "ng_version": True,
    "ng_onu": True,
    "ng_dynmaps": True,
    "mod_control": True,
    "mod_reglement": True,
    "mod_inspect": True,
    "mod_registre": True,
    "mod_clear": True,
    "config_bienvenue": True,
    "config_autorole": True,
    "config_exp": True,
    "config_role_reaction": True,
    "config_role_all": True,
    "exp_gestion": True,
    "exp_level": True,
    "exp_leaderboard": True,
    "ticket_panel_create": True,
    "ticket_panel_edit": True,
    "ticket_panel_delete": True,
    "ticket_panel_list": True,
    "ticket_close": True,
    "ticket_delete": True,
    "ticket_add": True,
    "ticket_ban": True,
    "ticket_rename": True,
    "ticket_remove": True,
    "invite_config": True,
    "invite_gestion": True,
    "invite_classement": True,
    "invite_user": True,
    "giveaway_create": True,
    "giveaway_manage": True,
    "giveaway_list": True,
    "dev_setngversion": True,
    "dev_botban": True,
    "dev_stats": True,
    "dev_message_recurrent": True,
    "dev_annonce": True,
    "dev_maintenance": True,
    "dev_kick": True,
    "dev_channel_stats": True,
    "alpha_stafflist": True,
    "alpha_nous_rejoindre": True,
    "alpha_test": True,
    "alpha_index": True,
    "alpha_regle_interne": True,
    "anniv_anniversaire": True,
    "anniv_kit": True,
    "anniv_classement": True,
    "anniv_inventaire": True,
    "anniv_fouiller": True,
    "anniv_admin_give": True,
    "anniv_admin_event": True,
    "anniv_admin_stats": True,
    "anniv_admin_points": True,
    "anniv_admin_dollars": True,
    "anniv_admin_logs": True,
    "anniv_admin_reset": True,
    "anniv_admin_reset_all": True,
    "anniv_admin_setup": True,
    "boutique": True,
    "wiki": True,
    "id_command": True,
    "ping": True,
    "info": True,
    "timestamp": True,
    "flex": True,
    "troll": True,
    "myserver": True,
    "rappel": True,
    "report": True,
}


async def seed():
    async with get_session() as session:
        for name, enabled in COMMANDS.items():
            session.add(CommandControl(command_name=name, enabled=enabled))
        await session.commit()
    print(f"✅ {len(COMMANDS)} commandes insérées en base.")


asyncio.run(seed())